# Generated by Django 3.2.4 on 2021-06-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owners',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pets',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='specialties',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vets',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vetspecialties',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='visits',
            options={'managed': False},
        ),
    ]
