# Generated by Django 3.2.4 on 2021-06-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0002_auto_20210620_2116'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owners',
            table='owners',
        ),
        migrations.AlterModelTable(
            name='pets',
            table='pets',
        ),
        migrations.AlterModelTable(
            name='specialties',
            table='specialties',
        ),
        migrations.AlterModelTable(
            name='types',
            table='types',
        ),
        migrations.AlterModelTable(
            name='vets',
            table='vets',
        ),
        migrations.AlterModelTable(
            name='vetspecialties',
            table='vet_specialties',
        ),
        migrations.AlterModelTable(
            name='visits',
            table='visits',
        ),
    ]
